### ISSUE TITLE
请问能将提取好特征的数据集放入百度网盘或者谷歌网盘吗

### ISSUE THREAD

**Issue by ttx213** [ttengwang/PDVC#11]
通过浏览器下载数据集网络会经常突然断开，导致数据集下载失败，还会有下载速度过慢的情况。

**Comment by ttengwang** [comment]
Ok, I will upload video features files to google drive latter.

**Comment by ttx213** [comment]
thank you : )

**Comment by ttengwang** [comment]
Please find the processed video features at this url.
https://drive.google.com/drive/folders/15Owgdwc1gJWYf_B9PcDiemq_478r9VJZ?usp=sharing
Now C3D features are available and TSN is still uploading.

**Comment by ttx213** [comment]
Thank you for your reply，I'll try as soon as possible




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttengwang/PDVC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 晚上8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ttengwang/PDVC] 请问能将提取好特征的数据集放入百度网盘或者谷歌网盘吗 (Issue #11)





 
Please find the processed video features at this url.
 https://drive.google.com/drive/folders/15Owgdwc1gJWYf_B9PcDiemq_478r9VJZ?usp=sharing
 Now C3D features are available and TSN is still uploading.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
