### ISSUE TITLE
C3D特征

### ISSUE THREAD

**Issue by cyy-1102** [ttengwang/PDVC#13]
您好！
        王老师，我查看.npy的C3D特征，发现每个特征的列数都是500，行数是不一样的。我想问您，列数和行数具体代表什么呢？每一行的特征是一个时间段的视频特征吗？列数和行数有关系吗？期待您的回复，谢谢您。

**Comment by ttengwang** [comment]
视频中的连续16帧输入到C3D获得一个frame-level feature vector。并以stride=8间隔采样，便获得多个特征向量。500是特征的维度，行数与视频帧数相关，可以认为：行数=视频总帧数/8。具体参考 http://activity-net.org/challenges/2016/download.html#c3d

对于TSN，特征提取过程稍有不同。不过行数也属于视频帧数或视频总时长呈正比。

**Comment by cyy-1102** [comment]
> 视频中的连续16帧输入到C3D获得一个frame-level feature vector。并以stride=8间隔采样，便获得多个特征向量。500是特征的维度，行数与视频帧数相关，可以认为：行数=视频总帧数/8。具体参考 http://activity-net.org/challenges/2016/download.html#c3d
> 
> 对于TSN，特征提取过程稍有不同。不过行数也属于视频帧数或视频总时长呈正比。

谢谢您王老师
