### ISSUE TITLE
关于Activitynet caption的TSN特征

### ISSUE THREAD

**Issue by cyy-1102** [ttengwang/PDVC#15]
王老师您好：
        data文件里的TSN特征是youcook2的特征，我想问一下，Activitynet caption的TSN特征在哪里找到呢

**Comment by ttengwang** [comment]
Please refer to https://github.com/ttengwang/PDVC/blob/main/data/anet/features/download_tsn_features.sh

**Comment by cyy-1102** [comment]
> Please refer to https://github.com/ttengwang/PDVC/blob/main/data/anet/features/download_tsn_features.sh

sorry，I misunderstood
