### ISSUE TITLE
I want to extract the ActivityNet Caption 2D features

### ISSUE THREAD

**Issue by cyy-1102** [ttengwang/PDVC#16]
dear wang:
        I want to extract the ActivityNet Caption 2D features, do you have the raw video? Or can I use TSN or TSP instead of 2D features？Looking forward to your reply，thank you！

**Comment by ttengwang** [comment]
Hi, in my experiments, TSP features (Fintuned R(2+1)D features) are better than TSN or 2D features.

And, ActivityNet organizer provided a google form to request the raw videos.
https://docs.google.com/forms/d/e/1FAIpQLSeKaFq9ZfcmZ7W0B0PbEhfbTHY41GeEgwsa7WobJgGUhn4DTQ/viewform

**Comment by cyy-1102** [comment]
> 



> Hi, in my experiments, TSP features (Fintuned R(2+1)D features) are better than TSN or 2D features.
> 
> And, ActivityNet organizer provided a google form to request the raw videos. https://docs.google.com/forms/d/e/1FAIpQLSeKaFq9ZfcmZ7W0B0PbEhfbTHY41GeEgwsa7WobJgGUhn4DTQ/viewform

thank you very much
