### ISSUE TITLE
Difference between para_METEOR and METEOR

### ISSUE THREAD

**Issue by cyy-1102** [ttengwang/PDVC#20]
hello, professor~
I want to ask you what's the difference between para_METEOR and METEOR

**Comment by ttengwang** [comment]
Hi, METEOR calculates the sentence-level similarity between generated captions and GT.

Para_METEOR calculates the similarity between the generated paragraph and GT paragraph, where the paragraphs are formed by sorting captions based on their starting time

**Comment by cyy-1102** [comment]
> Hi, METEOR calculates the sentence-level similarity between generated captions and GT.
> 
> Para_METEOR calculates the similarity between the generated paragraph and GT paragraph, where the paragraphs are formed by sorting captions based on their starting time

Thank you very much for your reply!
I recently used your baseline running experiment, I only focus on the performance of Dense Video Caption, can I ignore all the indicators with the prefix para_？Just focus on METEOR，Recall，Precision，soda_c？

**Comment by ttengwang** [comment]
Yes you can. The DVC task does not care about para_*.

**Comment by cyy-1102** [comment]
> Yes you can. The DVC task does not care about para_*.

thank you very much, professor！
