### ISSUE TITLE
BLEU4/CIDEr

### ISSUE THREAD

**Issue by cyy-1102** [ttengwang/PDVC#22]
I'm sorry to bother you again, professor. As for the two indicators BLEU4 and CIDEr of Dense Video Caption task in the paper, how can I get these two results？

**Comment by ttengwang** [comment]
Hi, youcan try the following command.
```bash
cd PDVC/densevid_eval3
python evaluate2018.py -v -s path/to/results.json
```

**Comment by cyy-1102** [comment]
> Hi, youcan try the following command.
> 
> ```shell
> cd PDVC/densevid_eval3
> python evaluate2018.py -v -s path/to/results.json
> ```

**Comment by cyy-1102** [comment]
> Hi, youcan try the following command.
> 
> ```shell
> cd PDVC/densevid_eval3
> python evaluate2018.py -v -s path/to/results.json
> ```

I'm sorry, professor, I don't seem to understand you. 
I modified your code, then trained the model, and tested my trained model using 'eval.py'. 
In the generated 'val.log' file: METEOR, Recall, Precision, soda_c, para_Bleu_1-4, para_METEOR, para_ROUGE_L, para_CIDEr. 
No file to generate result.json. 
Can BLEU4/CIDEr be calculated directly using 'evaluate2018.py'? Don't I need to change the code while training the model?

**Comment by ttengwang** [comment]
To find the results json, you do not need to modify the code. After training, I believe you could find some JSON files in `save/**/prediction/num*_epoch*_rerank*.json`. These files are the generated results at each epoch. 

After running `eval.py`, you can also find a json file in `save/**` which stores the generated captions of the best checkpoint. 

Use evaluate2018.py to evaluate these files, you will get the score of all types of metrics.

**Comment by cyy-1102** [comment]
> 

thank you very much, professor~

**Comment by cyy-1102** [comment]
> To find the result json, you do not need to modify the code. After training, I believe you could find some JSON files in `save/**/prediction/num*_epoch*_rerank*.json`. These files are the generated results at each epoch.
> 
> After running `eval.py`, you can also find a json file in `save/**/*.json` which stores the generated captions of the best checkpoint.
> 
> Use evaluate2018.py to evaluate these files, you will get the score of all types of metrics.

thank you very much, professor~
