### ISSUE TITLE
Should I change other parameters when I change batch_size?

### ISSUE THREAD

**Issue by RDCJ** [ttengwang/PDVC#23]
I cloned your repository and trained the model on ActivityNet. When I changed batch_size to a higher number, there was an error in the program. It happened at line 387 of pdvc.py, and after debugging, I found that the program ran there with an out-of-bounds in tensor. Should I change other parameters when I change batch_size?

**Comment by ttengwang** [comment]
See https://github.com/ttengwang/PDVC/issues/4

**Comment by ttengwang** [comment]
@RDCJ  But if you really need a version with batch size >1, I will update the code in my spare time asap.
