### ISSUE TITLE
How to further train on our own dataset?

### ISSUE THREAD

**Issue by pranavkamath14** [ttengwang/PDVC#24]
Hello,
Thank you so much for this amazing github repo. I wanted to use the pre-trained model and further train on my own dataset of videos and corresponding captions that I have. Do you have any suggestions on how I can do this?

**Comment by qt2139** [comment]
same question

**Comment by ttengwang** [comment]
1) prepare the video features (`.npy` files) following TSP and [convert_tsp_h5_to_npy.py](https://github.com/ttengwang/PDVC/blob/main/data/anet/features/convert_tsp_h5_to_npy.py).
2) constructe the follow annoations of your dataset. 
train_caption_file, val_caption_file, visual_feature_folder, gt_file_for_eval, gt_file_for_para_eval, dict_file
3) To further finetune the pre-trained PDVC (TSP), run `python train.py cfg_path=anet_tsp_pdvc.yml pretrain=full pretrain_path=path/to/ckpt`
