### ISSUE TITLE
"Running PDVC on Your Own Videos": Did i miss something?

### ISSUE THREAD

**Issue by Jeiyoon** [ttengwang/PDVC#26]
Hi 

Thank you for your great work

I loaded your pretrained model and ran your code using my video dataset (SumMe: video summarization benchmark),

but the results are really weird.

most captions doesn't represent visual features

 
<img width="957" alt="Capture" src="https://user-images.githubusercontent.com/56618962/167997518-a84d4f55-ea89-4314-9535-3ed0a0fd3ba5.PNG">

<img width="953" alt="Capture2" src="https://user-images.githubusercontent.com/56618962/167997527-5a7cc201-934a-443c-955b-281fb01b322b.PNG">

<img width="925" alt="Capture4" src="https://user-images.githubusercontent.com/56618962/167997790-e8e8ce93-62d1-44e0-8389-de85129632b9.PNG">

https://user-images.githubusercontent.com/56618962/167997537-5b21d8bc-a9b2-4e97-b735-93dfe36189e3.mp4

<img width="179" alt="Capture3" src="https://user-images.githubusercontent.com/56618962/167997616-ec3c5859-b905-40cd-b328-549f3025e887.PNG">

I just loaded your models and ran on the video datasets

most video captions are very weird

Did i miss something???

thank you

**Comment by coranholmes** [comment]
I have run the pre-trained model on CUHK Avenue Dataset, the captions also seem not as accurate as shown on the demo videos.

**Comment by Jeiyoon** [comment]
> @Jeiyoon Hi, did you get similar captions for the given demo video?

yeah It worked well on your demo video "xukun.mp4"

But all results on 50 vidieos in the dataset didnt't represent video modality features

**Comment by ttengwang** [comment]
I guess the reason lies in the domain gap between the pretraining videos and testing videos. The model may have a limited generatlization ability.

**Comment by Jeiyoon** [comment]
yeah I agree 

But really though, your paper and code are so nice 😊

Again thank you for your great work

**Comment by ttengwang** [comment]
😊😊

**Comment by 3244we** [comment]
应该是在运行的过程中报错了而已
