### ISSUE TITLE
i3d+vggish results

### ISSUE THREAD

**Issue by upccpu** [ttengwang/PDVC#27]
Hello professor,

When I reproduced your ‘i3d+vggish’ model, I found that i can not achieve the same results compared with the original paper. I don't know if there is something wrong with my settings.

Thinks

**Comment by ttengwang** [comment]
Could you please show me some detailed results?

**Comment by upccpu** [comment]
> Thanks for rely.
> 
> i list my final results below, it was captured from the 17 epoch. By the way, i didn't change the configrations in anet_c3d_pdvc.yml and anet_i3dvgg_pdvc.yml in the training procedure. 
> 
> Validation results of iter 165006: Bleu_1:0.14397184343673516 Bleu_2:0.07563979885710821 Bleu_3:0.03841529336432101 Bleu_4:0.018592074153146686 METEOR:0.07360392698576934 ROUGE_L:0.14248773409982254 CIDEr:0.2695501870140006 Recall:0.49363335351742516 Precision:0.5138465188800716 soda_c:0.05815482000571441 para_Bleu_1:0.4600347481728046 para_Bleu_2:0.2734444234216087 para_Bleu_3:0.16531830682605833 para_Bleu_4:0.10265513451045642 para_METEOR:0.14629477337476632 para_ROUGE_L:0.28967922834328586 para_CIDEr:0.17420500091591917
> 
> overall score of iter 165006: 0.13175874699148377

**Comment by ttengwang** [comment]
The results are normal since all scores you mentioned above are based on incomplete validation videos (5313 out of 5747). Around 434 videos got a METEOR of 0. 
The METEOR on 5313 videos are 0.0736039 * 5747/5313 = 7.96
