### ISSUE TITLE
about "pred_event_count"

### ISSUE THREAD

**Issue by coranholmes** [ttengwang/PDVC#28]
Thank you for the great work!

I am trying to run the model on different videos. But the "pred_event_count" seems always be 3, is this just a coincidence or is there something I have done wrongly? 

I am using the pretrained TSP features provided in the repo and the model work well on the demo video ("pred_event_count" is 3 as well).

**Comment by ttengwang** [comment]
Hi, it is normal for ActivityNet Captions, since this dataset has a large portion of videos containing 3 events. The model could predict more diverse event counts on YouCook2.

**Comment by coranholmes** [comment]
Thank you for the explanations.
