### ISSUE TITLE
NameError: name 'MSDA' is not defined

### ISSUE THREAD

**Issue by MrAccelerator** [ttengwang/PDVC#32]
![图片](https://user-images.githubusercontent.com/56375036/173172139-9cdca084-039d-4158-9cb7-6ce923621a19.png)
I installed the MultiScaleDeformableAttention as directed.
![图片](https://user-images.githubusercontent.com/56375036/173172177-f211e0b2-3ef2-41d1-b472-f18196351fb9.png)

**Comment by ttengwang** [comment]
Did you run `cond activate pdvc` to enter the custom environment?
