### ISSUE TITLE
About evaluation indicators

### ISSUE THREAD

**Issue by llljjj88** [ttengwang/PDVC#34]
I would like to ask if the evaluation index of the reproduction model of the paper is only described by video paragraphs. If I want to get the evaluation index of dense video caption

**Comment by ttengwang** [comment]
Sorry, I can't understand the question. Could you explain it a little bit more?

**Comment by llljjj88** [comment]
您好，那个关于评价指标的问题就是只有para_bleu的指标但是没有关于dense video caption的评价指标bleu的，那么我将如何才能得到这些指标呢，另外我复现的模型训练速度太久了，我可以修改哪些参数使得训练速度可以提升呢？感谢

**Comment by ttengwang** [comment]
V100上一个epoch时间在半个小时内, epoch设置为25左右, 一次实验是半天, 应该不会太久

**Comment by llljjj88** [comment]
谢谢您的回复   解决了我的困惑
