### ISSUE TITLE
评估过程失败，npy文件不存在。

### ISSUE THREAD

**Issue by Whutmc** [ttengwang/PDVC#36]
![image](https://user-images.githubusercontent.com/67730345/188164959-6d31593a-2f55-46aa-a6a1-c8abcf5292f9.png)

**Comment by ttengwang** [comment]
Please download the pre-extracted TSN features of YouCook2 using [download_yc2_tsn_features.sh](https://github.com/ttengwang/PDVC/blob/main/data/yc2/features/download_yc2_tsn_features.sh).

**Comment by wanghao14** [comment]
@Whutmc You need to change the default value of '--eval_caption_file'  in eval.py, otherwise it will find ActivityNet ae-val TSN features to do the evaluation which does not exist in your YouCook2 folder.

**Comment by NCU-MC** [comment]
作者您好，很高兴你能够回复我，我已经使用&nbsp;download_yc2_tsn_features.sh. 下载了 train、validation、test，训练没有问题，但运行eval.py进行评估就会报错。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Teng ***@***.***&gt;; 
发送时间: 2022年9月3日(星期六) 凌晨0:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ttengwang/PDVC] 评估过程失败，npy文件不存在。 (Issue #36)





 
Please download the pre-extracted TSN features of YouCook2 using download_yc2_tsn_features.sh.
