### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by llljjj88** [ttengwang/PDVC#38]
您好，我想问一下当我用PDVC with learnt proposals 训练出来的结果是与readme中Dense video caption（with learnt proposals）中的结果对比还是跟论文中Predicted proposals对比呢   Predicted proposals与learnt proposals又有什么不同呢？ 麻烦您能回答我这个困惑么

**Comment by ttengwang** [comment]
你好, 这两个词是等价的

**Comment by ttengwang** [comment]
代码跑出来的结果应当和readme报告的结果差不多

Readme中的结果与论文也大致相同, 除了soda这个指标(soda代码更新了)

**Comment by llljjj88** [comment]
您好，那么想请问您readme里面的结果是不是更新过了，readme里面的结果跟论文的结果还是有点差别，我发现readme里面的结果偏高一点

**Comment by ttengwang** [comment]
是, 在论文代码基础上优化了细节bug, 可以以原文为准

**Comment by llljjj88** [comment]
谢谢您 解决了我很大的困惑
