### ISSUE TITLE
Some questions regarding the dataset

### ISSUE THREAD

**Issue by MrAccelerator** [ttengwang/PDVC#39]
I would like to ask a question about the dataset. I looked at some papers, and I found that some papers are testing the modal performance on the ActivityNet Captions validation set, while some papers are testing the modal performance on the ActivityNet Captions test split. Is there the difference between ActivityNet Captions validation set and ActivityNet Captions test split?

**Comment by ttengwang** [comment]
The validation set and test set are both from the official splits[1] but the annotations of the test set is held by the ActivityNet Challenge organizers. Some early papers report performance on test split by evaluating on the [online test server](http://activity-net.org/challenges/2022/evaluation.html). However, the online server is only accessible during the Challenge, so some recent papers report the results on validation set as a compromise.

[1] R. Krishna, K. Hata, F. Ren, L. Fei-Fei, and J. C. Niebles, “Dense-captioning events in videos,” in Proc. IEEE Int. Conf. Comput. Vis., 2017, pp. 706-715.

**Comment by MrAccelerator** [comment]
Thanks for your quick response, this solved my confusion.
