### ISSUE TITLE
A question about demo video

### ISSUE THREAD

**Issue by adeljalalyousif** [ttengwang/PDVC#42]
Thanks for sharing your wonderful work.
 I haven't read your paper yet, so based on demo video, I have some questions:
1-  Is your PDVC model can be considered as live video captioning?
2- Is the caption is generated for each event directly without reading all video frames? 
3- How long does it take to generate caption for one event?

**Comment by ttengwang** [comment]
The model produces captions after reading all frames, so it is NOT a live captioning model.
Inference time largely depends on the video duration and your hardware. A reference for you is that captioning the demo video (lasting 1 minute) takes around 36s on Nvidia T4 GPU by running `test_and_visualize.sh`.

**Comment by adeljalalyousif** [comment]
Thank you so much

**Comment by adeljalalyousif** [comment]
Thank you so much
