### ISSUE TITLE
anet_tsn_pdvc  best model fail to load..

### ISSUE THREAD

**Issue by BMEI1314** [ttengwang/PDVC#5]
Thanks for the sharing of your wonderful work! I want to employ  your best tsn model   to run my video. But an error occurred while loading the model as follows:(maybe  released model parameters and structure do not match)
Loading model from save/anet_tsn_pdvc/model-best.pth
Traceback (most recent call last):
  File "eval.py", line 111, in <module>
    main(opt)
  File "eval.py", line 70, in main
    model.load_state_dict(loaded_pth['model'], strict=True)
  File "/data11/zq/vc_envs/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PDVC:
        size mismatch for transformer.pos_trans.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 512]).

**Comment by ttengwang** [comment]
Hi, thanks for reporting this issue. A new version of  anet_tsn_pdvc/model-best.pth is uploaded.

**Comment by BMEI1314** [comment]
Thank you very much for your quick reply and look forward to your follow-up work
