### ISSUE TITLE
error in ms_deformable_im2col_cuda: invalid device function

### ISSUE THREAD

**Issue by cyy-1102** [ttengwang/PDVC#6]
48%|████▊     | 2358/4917 [02:40<03:01, 14.12it/s]error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
 48%|████▊     | 2360/4917 [02:40<02:55, 14.58it/s]error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function
error in ms_deformable_im2col_cuda: invalid device function

Hello, what does the above situation mean when training the model? But the program can run

**Comment by cyy-1102** [comment]
I've solved it.Thank you

**Comment by ttengwang** [comment]
Hi @cyy-1102 , could you tell me how did you solve this problem? thanks!

**Comment by cyy-1102** [comment]
> Hi @cyy-1102 , could you tell me how did you solve this problem? thanks!

I'm sorry that I didn't see your problem until now. This problem may be due to the wrong CUDA/PyTorch versions and note that they match the Nvidia versions，you can try another version.
