### ISSUE TITLE
What is the difference between the learnt proposals and ground-true proposals

### ISSUE THREAD

**Issue by cyy-1102** [ttengwang/PDVC#7]
Hi @ttengwang ~
Thanks for the sharing of your wonderful work! What is the difference between the learnt proposals and ground-true proposals？

Thanks,
Yuanyuan

**Comment by ttengwang** [comment]
hi, for PDVC with learnt proposals, we predict both the location and the caption of each event. For PDVC with ground-truth proposals, the ground-truth locations of events are provided and we only need to predict their captions.

**Comment by cyy-1102** [comment]
> 
Thank you very much！

**Comment by cyy-1102** [comment]
> hi, for PDVC with learnt proposals, we predict both the location and the caption of each event. For PDVC with ground-truth proposals, the ground-truth locations of events are provided and we only need to predict their captions.

Thanks a lot！
