### ISSUE TITLE
没能复现readme中示例的效果

### ISSUE THREAD

**Issue by zmling22** [ttengwang/PDVC#8]
作者您好，我运行您的代码之后，对于坤坤跳舞的视屏，我并没有得到和您一样的效果大部分的时间caption的结果是"the credits of the video are shown"
![image](https://user-images.githubusercontent.com/39392690/144020951-0f28f009-2e31-4986-8c3c-7f8b2f75a6f4.png)
对于其他视屏，也是在大部分时间中都会显示这句话。请问是我哪一步错误了吗？我使用的就是您网盘中给的预训练模型

**Comment by ttengwang** [comment]
是否在gpu上运行？是否成功编译了pdvc/ops呢

**Comment by zmling22** [comment]
> 是否在gpu上运行？是否成功编译了pdvc/ops呢

感谢作者，重新编译ops后成功了
